# @format

kind: Service
apiVersion: v1
metadata:
  name: app-dashboard
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 3000
  selector:
    app: app-dashboard
